### PR TITLE
MatchAggregation replace in/nin param from String to Object

### PR DESCRIPTION
**Pull request by mcchris**

### CODE REVIEW

**Comment by benmccann** [comment]
@ebuchanan @kdkeck you guys have used aggregation more than i have. you think this is a good change? looks like it to me, but wanted to double check before i merge

**Comment by kdkeck** [comment]
The more I look at it, the more I think the parent commit went the wrong way here.  There's a whole lot of code here that looks a lot like code in DBQuery, but probably containing a lot of bugs and inconsistencies.  That can all be avoided by explicitly delegating to DBQuery, like this:
```java
public class MatchAggregation extends AggregatePipelineOperation {
    private Query query;
    public MatchAggregation() {
        this(DBQuery.empty());
    }
    public MatchAggregation(Query query) {
        this.query = query;
    }
    @Override
    public DBObject apply(JacksonDBCollection dbCollection) {
        return new BasicDBObject("$match", dbCollection.serializeQuery(query));
    }
}
```
Except the overridden `apply` method doesn't provide the `JacksonDBCollection` parameter, so that needs to change as well...

Or even better, make `AggregatePipelineOperation` an interface, so we can do something more like:
```java
public class MatchAggregation extends DBQuery.AbstractBuilder<MatchAggregation>
        implements AggregatePipelineOperation {
    private Query query;
    public MatchAggregation() {
        this(DBQuery.empty());
    }
    public MatchAggregation(Query query) {
        this.query = query;
    }
    @Override
    protected MatchAggregation put(String op, QueryCondition value) {
        query.put(op, value);
        return this;
    }
    @Override
    protected MatchAggregation put(String field, String op, QueryCondition value) {
        query.put(field, op, value);
        return this;
    }
    @Override
    protected MatchAggregation putGroup(String op, Query... expressions) {
        query.putGroup(op, expressions);
        return this;
    }
    @Override
    public DBObject apply(JacksonDBCollection dbCollection) {
        return new BasicDBObject("$match", dbCollection.serializeQuery(query));
    }
}
```

**Comment by kdkeck** [comment]
I believe this PR has been obsoleted by #91.

**Comment by benmccann** [comment]
Yes, you're right. Thanks

**Pull request closed without merging**
